from Repositorios.InterfaceRepositorio import InterfaceRepositorio
from Modelos.ExperienciaTuristica import ExperienciaTuristica
class RepositorioExperienciaTurustica(InterfaceRepositorio[ExperienciaTuristica]):
    pass